version: '3.8'

x-default-app:
  &default-app
    build:
      dockerfile: ./Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - ./src:/code/src
    stdin_open: true
    tty: true

services:
  django:
    <<: *default-app
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy

  celery:
    <<: *default-app
    command: celery -A src.config.celery worker -l info
    depends_on:
      - django
      - rabbitmq

  postgres:
    image: "postgres:16-alpine"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=waltz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  postgres_data:
